---
- name: Install Apache2 on Amazon Linux
  hosts: clientserver
  become: yes
  tasks:
    - name: Update the package manager
      yum:
        name: "*"
        state: latest

    - name: Install Apache (httpd)
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is running and enabled on boot
      service:
        name: httpd
        state: started
        enabled: yes

