---
- name: Check PostgreSQL version
  hosts: clientserver
  become: yes
  tasks:
    - name: Check PostgreSQL version
      command: psql --version
      register: pgsql_version
      ignore_errors: yes

    - name: Debug PostgreSQL version
      debug:
        msg: "{{ pgsql_version.stdout }}"
      when: pgsql_version.rc == 0

    - name: PostgreSQL is not installed
      debug:
        msg: "PostgreSQL is not installed on this host."
      when: pgsql_version.rc != 0

    - name: Check if PostgreSQL 14 is installed
      debug:
        msg: "PostgreSQL 14 is installed."
      when: "'psql (PostgreSQL) 14' in pgsql_version.stdout"

    - name: Check if PostgreSQL 14 is not installed
      debug:
        msg: "PostgreSQL 14 is not installed."
      when: "'psql (PostgreSQL) 14' not in pgsql_version.stdout"

