- name: Install and configure PostgreSQL 14 from source
  hosts: local
  become: true

  tasks:
    - name: Install required build dependencies
      package:
        name:
          - gcc
          - make
          - readline-devel
          - zlib-devel
          - openssl-devel
          - libxml2-devel
          - libxslt-devel
          - openldap-devel
          - pam-devel
        state: present

    - name: Ensure postgres user exists
      ansible.builtin.user:
        name: postgres
        state: present

    - name: Set ownership of PostgreSQL base directory
      ansible.builtin.file:
        path: /var/lib/pgsql
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'

    - name: Remove existing PostgreSQL data directory if needed
      ansible.builtin.file:
        path: /var/lib/pgsql/14/data
        state: absent
      become: true
      ignore_errors: yes

    - name: Create PostgreSQL data directory
      ansible.builtin.file:
        path: /var/lib/pgsql/14/data
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Download PostgreSQL 14 source code
      get_url:
        url: https://ftp.postgresql.org/pub/source/v14.0/postgresql-14.0.tar.gz
        dest: /tmp/postgresql-14.0.tar.gz

    - name: Extract PostgreSQL source code
      ansible.builtin.command:
        cmd: "tar -xf /tmp/postgresql-14.0.tar.gz -C /tmp/"

    - name: Configure PostgreSQL
      ansible.builtin.command:
        cmd: "./configure --prefix=/usr/local/pgsql-14.0"
        chdir: /tmp/postgresql-14.0

    - name: Build PostgreSQL
      ansible.builtin.command:
        cmd: "make"
        chdir: /tmp/postgresql-14.0

    - name: Install PostgreSQL
      ansible.builtin.command:
        cmd: "make install"
        chdir: /tmp/postgresql-14.0

    - name: Ensure /etc/profile.d directory exists
      ansible.builtin.file:
        path: /etc/profile.d
        state: directory
        mode: '0755'

    - name: Add PostgreSQL binaries to system PATH
      ansible.builtin.copy:
        dest: /etc/profile.d/pgsql.sh
        content: |
          # Add PostgreSQL binaries to PATH
          export PATH=$PATH:/usr/local/pgsql-14.0/bin
        mode: '0755'

    - name: Source PostgreSQL PATH
      ansible.builtin.shell:
        cmd: "source /etc/profile.d/pgsql.sh"
      ignore_errors: yes

    - name: Initialize PostgreSQL database
      ansible.builtin.command:
        cmd: "/usr/local/pgsql-14.0/bin/initdb -D /var/lib/pgsql/14/data"
      become_user: postgres

    - name: Ensure correct ownership of PostgreSQL directories
      ansible.builtin.file:
        path: /var/lib/pgsql/14/data
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Ensure correct ownership of PostgreSQL log file
      ansible.builtin.file:
        path: /var/log/postgresql-14.log
        state: touch
        owner: postgres
        group: postgres
        mode: '0644'

    - name: Create systemd service file for PostgreSQL
      ansible.builtin.copy:
        dest: /etc/systemd/system/postgresql-14.service
        content: |
          [Unit]
          Description=PostgreSQL 14 database server
          Documentation=https://www.postgresql.org/docs/14/static/
          After=network.target

          [Service]
          Type=forking
          User=postgres
          Group=postgres
          ExecStart=/usr/local/pgsql-14.0/bin/pg_ctl start -D /var/lib/pgsql/14/data -l /var/log/postgresql-14.log
          ExecStop=/usr/local/pgsql-14.0/bin/pg_ctl stop -D /var/lib/pgsql/14/data
          ExecReload=/usr/local/pgsql-14.0/bin/pg_ctl reload -D /var/lib/pgsql/14/data
          TimeoutSec=300

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start PostgreSQL service
      ansible.builtin.service:
        name: postgresql-14
        state: started
        enabled: yes

    - name: Create PostgreSQL user
      ansible.builtin.command:
        cmd: "/usr/local/pgsql-14.0/bin/createuser pguser"
      become_user: postgres
      args:
        creates: /var/lib/pgsql/14/data/global/pg_authid

    - name: Set PostgreSQL user password
      ansible.builtin.command:
        cmd: "/usr/local/pgsql-14.0/bin/psql -c \"ALTER USER pguser WITH PASSWORD 'pgpassword';\""
      become_user: postgres

    - name: Create PostgreSQL database
      ansible.builtin.command:
        cmd: "/usr/local/pgsql-14.0/bin/createdb mydb"
      become_user: postgres
      args:
        creates: /var/lib/pgsql/14/data/base/mydb

    - name: Configure PostgreSQL for password authentication
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/14/data/pg_hba.conf
        regexp: '^host\s+all\s+all\s+127.0.0.1/32\s+ident$'
        line: 'host    all             all             127.0.0.1/32            md5'
        state: present

    - name: Restart PostgreSQL service
      ansible.builtin.service:
        name: postgresql-14
        state: restarted

